#ifndef JAYD_DEFAULTAUDIOSETTINGS_H
#define JAYD_DEFAULTAUDIOSETTINGS_H

#define DEFAULT_BUFFSIZE 1024 //number of samples in the buffer
#define DEFAULT_SAMPLERATE 16000
#define DEFAULT_BYTESPERSAMPLE 2
#define DEFAULT_NUMCHANNELS 2

#endif